"""Turn answers into files, and refuse to write a config that will not load."""

import json
import os
import tempfile
from pathlib import Path
from typing import Any

import yaml

from dbs_vector.core.model_registry import ModelContract
from dbs_vector.services.initializer.answers import InitAnswers
from dbs_vector.services.initializer.kinds import EngineKind

_DEFAULT_NPROBES = 20


def table_name_for(engine_name: str) -> str:
    return f"{engine_name.replace('-', '_')}_vault"


def workflow_for(engine_name: str) -> str:
    return f"{engine_name.replace('-', '_')}_search"


def profile_name_for(engine_name: str, tier_key: str) -> str:
    return f"{engine_name}-{tier_key}"


def build_config_dict(
    answers: InitAnswers,
    profile: dict[str, int],
    contract: ModelContract,
    kind: EngineKind,
) -> dict[str, Any]:
    """Assemble the full config mapping. No I/O.

    Deliberately absent from the engine block:
      * `similarity_floor` - deployment-local calibration evidence; every
        engine ships unset and a wizard must not invent one.
      * `family` - defaults to mapper_type.
    """
    profile_name = profile_name_for(answers.engine_name, answers.tier_key)

    engine: dict[str, Any] = {
        "description": f"Markdown documentation chunks ({answers.model_key} embeddings).",
        "model": answers.model_key,
        "mapper_type": kind.mapper_type,
        "chunker_type": kind.chunker_type,
        "table_name": table_name_for(answers.engine_name),
        "workflow": workflow_for(answers.engine_name),
        "tuning_profile": profile_name,
    }
    if answers.passage_prefix:
        engine["passage_prefix"] = answers.passage_prefix
    if answers.query_prefix:
        engine["query_prefix"] = answers.query_prefix

    engine = kind.build_engine_block(engine, answers.kind)

    return {
        "system": {"db_path": answers.db_path, "nprobes": _DEFAULT_NPROBES},
        "profiles": {profile_name: dict(profile)},
        "engines": {answers.engine_name: engine},
    }


def dump_config_yaml(config: dict[str, Any], model_key: str, budget_gb: float) -> str:
    """Serialize with a provenance header. sort_keys=False keeps system ->
    profiles -> engines, which is the order the guide explains them in."""
    header = (
        "# Generated by `dbs-vector init`.\n"
        f"# Profile derived from the '{model_key}' model contract and a\n"
        f"# detected {budget_gb:.1f} GB Metal budget. See docs/README_PROFILES.md\n"
        "# and docs/README_CONFIGURATION.md.\n"
    )
    body = yaml.safe_dump(config, sort_keys=False, default_flow_style=False, allow_unicode=True)
    return header + body


def validate_rendered_config(yaml_text: str) -> None:
    """Round-trip the SERIALIZED bytes through the real loader.

    Validating the text rather than the dict means a YAML-level bug (a
    mis-quoted prefix, a stringified int) fails here rather than on the
    user's next command. Raises ValueError with the loader's own message.
    """
    from dbs_vector.config import load_settings

    with tempfile.TemporaryDirectory() as tmp:
        probe = Path(tmp) / "config.yaml"
        probe.write_text(yaml_text, encoding="utf-8")
        load_settings(str(probe), validate=True)


def write_atomic(path: Path, text: str) -> None:
    """Write via a temp file in the destination directory, then os.replace.
    A crash mid-write leaves the original intact."""
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp_name = tempfile.mkstemp(dir=str(path.parent), suffix=".tmp")
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            handle.write(text)
        os.replace(tmp_name, path)
    except BaseException:
        Path(tmp_name).unlink(missing_ok=True)
        raise


def dump_mcp_json(config: dict[str, Any]) -> str:
    return json.dumps(config, indent=2) + "\n"


def read_mcp_config(path: Path) -> dict[str, Any] | None:
    """Load an existing MCP config. None when absent.

    A malformed file RAISES rather than being treated as empty: silently
    starting from scratch would drop the user's other servers. run_init
    catches this and offers a different destination (Task 8) - the recovery
    path §9 promises - rather than letting it abort the wizard.
    """
    if not path.exists():
        return None

    # Every failure mode must surface as ValueError: run_init's recovery
    # prompt and the CLI's handler both catch ValueError only. Verified to
    # escape a JSONDecodeError-only guard: IsADirectoryError (path is a
    # directory), UnicodeDecodeError (invalid UTF-8), PermissionError
    # (unreadable) - each of which would otherwise reach the user as a
    # traceback.
    try:
        raw = path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError) as exc:
        raise ValueError(
            f"{path} could not be read ({exc}). Fix it, or choose a different "
            f"destination, so your other MCP servers are not lost."
        ) from exc

    try:
        data = json.loads(raw)
    except json.JSONDecodeError as exc:
        raise ValueError(
            f"{path} could not be parsed as JSON ({exc}). Fix it, or choose a "
            f"different destination, so your other MCP servers are not lost."
        ) from exc

    if not isinstance(data, dict):
        raise ValueError(f"{path} must contain a JSON object at the top level.")

    # `{"mcpServers": []}` parses fine but would blow up at assignment time:
    # dict.setdefault returns the EXISTING list, and list["dbs-vector"] = ...
    # raises TypeError, which no caller catches.
    servers = data.get("mcpServers")
    if servers is not None and not isinstance(servers, dict):
        raise ValueError(
            f'{path} has an "mcpServers" key of type {type(servers).__name__}, '
            f"but it must be a JSON object."
        )
    return data


def merge_mcp_config(
    existing: dict[str, Any] | None,
    install_dir: str,
    config_path: str,
    server_name: str = "dbs-vector",
) -> dict[str, Any]:
    """Add or replace one server, preserving every other key verbatim.

    `--config-file` is passed as the GLOBAL option, BEFORE the `mcp`
    subcommand. The subcommand-level form (`mcp --config-file X`) still runs
    the Typer callback first with its own `config.yaml` default, so the
    spawned server loads and validates whatever config.yaml happens to sit in
    its cwd before the override applies.

    `--allow-raw-queries` is deliberately not emitted: it exposes literal PII
    from the SQL raw_query column and has no effect on a document engine.
    """
    merged: dict[str, Any] = json.loads(json.dumps(existing)) if existing else {}
    # NOT setdefault: it returns the existing value even when that value is a
    # list, and the assignment below would then raise TypeError. read_mcp_config
    # already rejects a non-object mcpServers; this keeps merge total for any
    # other caller.
    servers = merged.get("mcpServers")
    if not isinstance(servers, dict):
        servers = {}
    merged["mcpServers"] = servers
    servers[server_name] = {
        "command": "uv",
        "args": [
            "--directory",
            install_dir,
            "run",
            "dbs-vector",
            "--config-file",
            config_path,
            "mcp",
        ],
    }
    return merged
