"""Turn answers into files, and refuse to write a config that will not load."""

import json
import os
import tempfile
from pathlib import Path
from typing import Any

import yaml

from dbs_vector.core.model_registry import ModelContract
from dbs_vector.services.initializer.answers import InitAnswers
from dbs_vector.services.initializer.kinds import EngineKind

_DEFAULT_NPROBES = 20


def table_name_for(engine_name: str) -> str:
    return f"{engine_name.replace('-', '_')}_vault"


def workflow_for(engine_name: str) -> str:
    return f"{engine_name.replace('-', '_')}_search"


def profile_name_for(engine_name: str, tier_key: str) -> str:
    return f"{engine_name}-{tier_key}"


def build_config_dict(
    answers: InitAnswers,
    profile: dict[str, int],
    contract: ModelContract,
    kind: EngineKind,
) -> dict[str, Any]:
    """Assemble the full config mapping. No I/O.

    Deliberately absent from the engine block:
      * `similarity_floor` - deployment-local calibration evidence; every
        engine ships unset and a wizard must not invent one.
      * `family` - defaults to mapper_type.
    """
    profile_name = profile_name_for(answers.engine_name, answers.tier_key)

    engine: dict[str, Any] = {
        "description": f"Markdown documentation chunks ({answers.model_key} embeddings).",
        "model": answers.model_key,
        "mapper_type": kind.mapper_type,
        "chunker_type": kind.chunker_type,
        "table_name": table_name_for(answers.engine_name),
        "workflow": workflow_for(answers.engine_name),
        "tuning_profile": profile_name,
    }
    if answers.passage_prefix:
        engine["passage_prefix"] = answers.passage_prefix
    if answers.query_prefix:
        engine["query_prefix"] = answers.query_prefix

    engine = kind.build_engine_block(engine, answers.kind)

    return {
        "system": {"db_path": answers.db_path, "nprobes": _DEFAULT_NPROBES},
        "profiles": {profile_name: dict(profile)},
        "engines": {answers.engine_name: engine},
    }


def dump_config_yaml(config: dict[str, Any], model_key: str, budget_gb: float) -> str:
    """Serialize with a provenance header. sort_keys=False keeps system ->
    profiles -> engines, which is the order the guide explains them in."""
    header = (
        "# Generated by `dbs-vector init`.\n"
        f"# Profile derived from the '{model_key}' model contract and a\n"
        f"# detected {budget_gb:.1f} GB Metal budget. See docs/README_PROFILES.md\n"
        "# and docs/README_CONFIGURATION.md.\n"
    )
    body = yaml.safe_dump(config, sort_keys=False, default_flow_style=False, allow_unicode=True)
    return header + body


def validate_rendered_config(yaml_text: str) -> None:
    """Round-trip the SERIALIZED bytes through the real loader.

    Validating the text rather than the dict means a YAML-level bug (a
    mis-quoted prefix, a stringified int) fails here rather than on the
    user's next command. Raises ValueError with the loader's own message.
    """
    from dbs_vector.config import load_settings

    with tempfile.TemporaryDirectory() as tmp:
        probe = Path(tmp) / "config.yaml"
        probe.write_text(yaml_text, encoding="utf-8")
        load_settings(str(probe), validate=True)


def write_atomic(path: Path, text: str) -> None:
    """Write via a temp file in the destination directory, then os.replace.
    A crash mid-write leaves the original intact."""
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp_name = tempfile.mkstemp(dir=str(path.parent), suffix=".tmp")
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            handle.write(text)
        os.replace(tmp_name, path)
    except BaseException:
        Path(tmp_name).unlink(missing_ok=True)
        raise


def dump_mcp_json(config: dict[str, Any]) -> str:
    return json.dumps(config, indent=2) + "\n"
