import math
from typing import Any

import lancedb  # type: ignore[import-untyped]
import numpy as np
from loguru import logger
from numpy.typing import NDArray

from dbs_vector.core.ports import IStoreMapper

# Strategy switch only: at or below this many matched ids we prefilter with
# `id IN (...)`. Above it we use an exact vector-only full-scan fallback.
_TABLE_FILTER_PREFILTER_CAP = 50_000


class LanceDBStore:
    """
    High-performance, Arrow-native storage backend using LanceDB.
    """

    def __init__(
        self,
        db_path: str,
        table_name: str,
        vector_dimension: int,
        mapper: IStoreMapper,
        nprobes: int = 20,
    ) -> None:
        self.db_path = db_path
        self.table_name = table_name
        self.vector_dimension = vector_dimension
        self.nprobes = nprobes
        self.mapper = mapper
        self.schema = mapper.schema

        self._hybrid_ok: bool | None = None  # None=untried, True=works, False=skip
        # Last table version seen by search(); when checkout_latest() advances
        # it (possibly via a commit from ANOTHER process), _hybrid_ok resets.
        self._table_version: int | None = None

        self.db = lancedb.connect(db_path)
        # Use exist_ok to open existing tables rather than overwriting on app start
        try:
            self.table = self.db.create_table(self.table_name, schema=self.schema, exist_ok=True)
        except ValueError as e:
            if "schema does not match" in str(e).lower() or "schema" in str(e).lower():
                raise ValueError(
                    f"Schema mismatch detected for table '{self.table_name}'. "
                    f"The database schema has been updated (e.g., new vector dimensions or fields like 'workflow'). "
                    f"Please rebuild your index by running: uv run dbs-vector ingest <path> --type <engine> --rebuild --force"
                ) from e
            raise

    def clear(self) -> None:
        """Drops the table and recreates it with an empty schema."""
        self.db.drop_table(self.table_name, ignore_missing=True)  # pyright: ignore[reportCallIssue]
        self.table = self.db.create_table(self.table_name, schema=self.schema)
        # FTS index is gone after table drop/recreate — allow hybrid retry.
        self._hybrid_ok = None

    def ingest_chunks(self, chunks: list[Any], vectors: NDArray[np.float32], workflow: str) -> None:
        """Constructs an Arrow RecordBatch to completely bypass Python iterators."""
        if not chunks:
            return

        arrow_batch = self.mapper.to_record_batch(chunks, vectors, workflow)

        self.table.add(arrow_batch)

    def compact(self) -> None:
        """Merges fragment Lance files generated by delta-updates."""
        self.table.optimize()

    def create_indices(self) -> None:
        """Generates dynamic IVF_PQ vector indices and Tantivy FTS indices."""
        total_rows = len(self.table)

        # 1. Vector Indexing (Cosine)
        if total_rows > 256:
            # Scale partitions dynamically
            num_partitions = max(1, min(256, int(math.sqrt(total_rows))))
            self.table.create_index(
                metric="cosine",
                vector_column_name="vector",
                index_type="IVF_PQ",
                num_partitions=num_partitions,
                num_sub_vectors=min(16, self.vector_dimension // 8),
            )

        # 2. Tantivy FTS Indexing (Hybrid Search)
        try:
            self.table.create_fts_index("text", replace=True)
        except Exception as e:
            logger.warning("FTS indexing failed (tantivy missing?): {}", e)

        # FTS index may now exist (or have been replaced) — allow hybrid retry.
        self._hybrid_ok = None

    def refresh_fts(self) -> None:
        """Rebuild ONLY the Tantivy FTS index (no IVF_PQ work).

        Called on the watcher's 60s timer so newly written rows reach the FTS
        leg of hybrid search within a minute. The vector leg finds them
        immediately without any index work.
        """
        try:
            self.table.create_fts_index("text", replace=True)
        except Exception as e:  # noqa: BLE001 — must never kill the watcher worker
            logger.warning("FTS refresh failed for '{}': {}", self.table_name, e)
        # The index may now exist or have been replaced — allow hybrid retry.
        self._hybrid_ok = None

    def delete_by_source(self, source: str) -> None:
        """Delete every row for one source path (predicate delete)."""
        safe = source.replace("'", "''")
        self.table.delete(f"source = '{safe}'")

    def get_existing_hashes(self) -> set[str]:
        """Returns all existing content hashes, projecting a single column
        via LanceDB's query builder to avoid materialising the vector column."""
        # Same freshness contract as search()/count_matching()/scan(): a
        # long-lived process must see rows committed elsewhere.
        self.table.checkout_latest()
        if len(self.table) == 0:
            return set()

        tbl = self.table.search().select(["content_hash"]).to_arrow()
        return set(tbl.column("content_hash").to_pylist())

    def _matching_table_ids(self, table_filter: str) -> list[str]:
        """Row ids whose tables contain table_filter after exact normalization."""
        from dbs_vector.core.models import _normalize_table_name

        needle = _normalize_table_name(table_filter)
        if not needle:
            return []

        rows = self.table.search().select(["id", "tables"]).to_arrow().to_pylist()
        ids: list[str] = []
        for row in rows:
            tables = row.get("tables")
            if isinstance(tables, list) and needle in {_normalize_table_name(t) for t in tables}:
                ids.append(row["id"])
        return ids

    def search(
        self,
        query: str,
        query_vector: NDArray[np.float32],
        source_filter: str | None = None,
        limit: int = 5,
        **kwargs: Any,
    ) -> list[Any]:
        """Executes Hybrid (or pure Vector) search, filtering natively in Rust."""

        # Pick up rows committed by another process (e.g., a `dbs-vector ingest`
        # run while the MCP server is already loaded). LanceDB Table objects
        # snapshot the dataset version at open-time; without this refresh, a
        # long-lived SearchService would never see new rows.
        self.table.checkout_latest()

        # A version advance can also mean a new/replaced FTS index (index
        # creation commits a version in Lance) — including one built by that
        # other ingest process. Reset the hybrid cache so a failure observed
        # before the index existed cannot stick for this process's lifetime.
        version = self.table.version
        if version != self._table_version:
            self._table_version = version
            self._hybrid_ok = None

        min_time = kwargs.get("min_time")
        min_lock_time = kwargs.get("min_lock_time")
        table_filter = kwargs.get("table_filter")
        table_ids: list[str] | None = None
        oversized = False
        fetch_limit = limit
        if table_filter:
            table_ids = self._matching_table_ids(table_filter)
            if not table_ids:
                return []
            oversized = len(table_ids) > _TABLE_FILTER_PREFILTER_CAP
            if oversized:
                # No efficient prefilter for this many ids. Use vector-only
                # full-scan ranking below; hybrid dedupes after LanceDB applies
                # limit, so duplicate ids from both legs could hide tail rows.
                fetch_limit = self.table.count_rows()
                logger.debug(
                    "table_filter '{}' matched {} fingerprints (> {} cap); "
                    "using exact vector-only full-scan ranking fallback.",
                    table_filter,
                    len(table_ids),
                    _TABLE_FILTER_PREFILTER_CAP,
                )

        # When `table_filter` is set the candidate set is highly selective
        # (typically <5% of rows) and lives across IVF partitions the default
        # nprobes will not scan, silently returning zero results. Bypass the
        # IVF index for exact flat search in that case.
        bypass_index = table_filter is not None

        def _apply_filters(op: Any) -> Any:
            if source_filter:
                safe_filter = source_filter.replace("'", "''")
                op = op.where(f"source = '{safe_filter}'", prefilter=True)
            if min_time is not None:
                op = op.where(f"execution_time_ms >= {min_time}", prefilter=True)
            if min_lock_time is not None:
                op = op.where(f"lock_time_sec >= {min_lock_time}", prefilter=True)
            if table_ids is not None and not oversized:
                quoted = ", ".join("'" + i.replace("'", "''") + "'" for i in table_ids)
                op = op.where(f"id IN ({quoted})", prefilter=True)
            return op

        def _build_vector() -> Any:
            # Filters must be applied before bypass_vector_index()/nprobes().
            # Applying them after the index strategy can demote prefilter
            # behavior and let unfiltered rows leak through LanceDB hybrid
            # search when `table_filter` triggers bypass mode.
            op = self.table.search(query_vector).metric("cosine")  # pyright: ignore[reportAttributeAccessIssue]
            op = _apply_filters(op)
            if bypass_index:
                op = op.bypass_vector_index()
            else:
                op = op.nprobes(self.nprobes)
            return op.limit(fetch_limit)

        def _build_hybrid() -> Any:
            op = self.table.search(query_type="hybrid").vector(query_vector).text(query)
            op = _apply_filters(op)
            if bypass_index:
                op = op.bypass_vector_index()
            else:
                op = op.nprobes(self.nprobes)
            return op.limit(fetch_limit)

        # Hybrid requires an FTS index. Once we learn it is unavailable, skip
        # the build+raise on every subsequent query; the cache is reset wherever
        # the FTS index can change (create_indices / clear).
        # Oversized table_filter uses vector-only: hybrid dedupes after `limit`,
        # which could drop the lowest-ranked unique matching rows from a
        # limit=count_rows() fetch. Vector-only returns one row per id.
        if self._hybrid_ok is False or oversized:
            search_op = _build_vector()
            results_df = search_op.to_polars()
        else:
            try:
                search_op = _build_hybrid()
                results_df = search_op.to_polars()
                self._hybrid_ok = True
            except (ValueError, RuntimeError, ImportError, OSError) as e:
                # Narrowed from bare Exception so a programming error doesn't
                # silently degrade to vector-only. Verified against LanceDB
                # 0.30.2: FTS-absent raises RuntimeError ("Cannot perform full
                # text search unless an INVERTED index has been created");
                # ImportError covers a legacy tantivy index dir when the
                # tantivy wheel fails to import (lancedb/query.py:1556-1561);
                # OSError (incl. FileNotFoundError) covers corrupt/missing
                # index files mapped from LanceError(IO). Degrading the HYBRID
                # leg on IO errors is safe: if the dataset itself is broken,
                # the vector fallback raises too and THAT exception propagates.
                self._hybrid_ok = False
                logger.warning(
                    "Hybrid search unavailable or failed ({}), falling back to pure vector", e
                )
                search_op = _build_vector()
                results_df = search_op.to_polars()

        # Hybrid search merges vector + FTS branches and can yield the same
        # `id` from both. Dedupe after LanceDB applies `limit`; this may return
        # fewer than `limit` rows, but avoids over-fetching latency for the
        # production duplicate rate.
        if "id" in results_df.columns:
            results_df = results_df.unique(subset=["id"], keep="first", maintain_order=True)

        mapped_results: list[Any] = []
        normalized_table = None
        if table_filter:
            from dbs_vector.core.models import _normalize_table_name

            normalized_table = _normalize_table_name(table_filter)

        for row in results_df.iter_rows(named=True):
            if source_filter and row.get("source") != source_filter:
                continue
            if min_time is not None:
                execution_time_ms = row.get("execution_time_ms")
                if (
                    not isinstance(execution_time_ms, (int, float))
                    or isinstance(execution_time_ms, bool)
                    or execution_time_ms < min_time
                ):
                    continue
            if min_lock_time is not None:
                lock_time_sec = row.get("lock_time_sec")
                if (
                    not isinstance(lock_time_sec, (int, float))
                    or isinstance(lock_time_sec, bool)
                    or lock_time_sec < min_lock_time
                ):
                    continue
            if normalized_table:
                tables = row.get("tables")
                if not isinstance(tables, list) or normalized_table not in {
                    _normalize_table_name(t) for t in tables
                }:
                    continue
            rel = row.get("_relevance_score")
            dist = row.get("_distance")
            score = float(rel) if isinstance(rel, float) else None
            distance = float(dist) if isinstance(dist, float) else None
            mapped_results.append(self.mapper.from_polars_row(row, score=score, distance=distance))

        return mapped_results[:limit]

    def count_matching(
        self,
        source_filter: str | None = None,
        **kwargs: Any,
    ) -> int:
        """Count rows matching the same filters used by search."""
        self.table.checkout_latest()

        min_time = kwargs.get("min_time")
        min_lock_time = kwargs.get("min_lock_time")
        table_filter = kwargs.get("table_filter")

        if table_filter:
            return self._count_matching_scan(source_filter, min_time, min_lock_time, table_filter)

        predicates: list[str] = []
        if source_filter:
            safe = source_filter.replace("'", "''")
            predicates.append(f"source = '{safe}'")
        if min_time is not None:
            predicates.append(f"execution_time_ms >= {min_time}")
        if min_lock_time is not None:
            predicates.append(f"lock_time_sec >= {min_lock_time}")

        if not predicates:
            return self.table.count_rows()

        where_clause = " AND ".join(predicates)
        return self.table.count_rows(filter=where_clause)

    def _count_matching_scan(
        self,
        source_filter: str | None,
        min_time: float | None,
        min_lock_time: float | None,
        table_filter: str,
    ) -> int:
        """Exact count for table_filter using projected in-memory comparison."""
        from dbs_vector.core.models import _normalize_table_name

        needle = _normalize_table_name(table_filter)
        if not needle:
            return 0

        cols = ["tables", "source", "execution_time_ms", "lock_time_sec"]
        available = [c for c in cols if c in self.schema.names]
        rows = self.table.search().select(available).to_arrow().to_pylist()
        n = 0
        for row in rows:
            if source_filter and row.get("source") != source_filter:
                continue
            if min_time is not None and (row.get("execution_time_ms") or 0) < min_time:
                continue
            if min_lock_time is not None and (row.get("lock_time_sec") or 0) < min_lock_time:
                continue
            tables = row.get("tables")
            if isinstance(tables, list) and needle in {_normalize_table_name(t) for t in tables}:
                n += 1
        return n

    def scan(self, columns: list[str] | None = None) -> Any:
        """Read all rows as a pyarrow.Table, projecting out vector/workflow.

        Mirrors get_existing_hashes' column-projected query (avoids
        materialising the embedding vector) but selects the full analytical
        column set. checkout_latest() first so a long-lived MCP server sees
        rows committed by a separate ingest process.
        """
        self.table.checkout_latest()
        if columns is None:
            columns = [c for c in self.schema.names if c not in ("vector", "workflow")]
        return self.table.search().select(columns).to_arrow()
