import pytest
import yaml

from dbs_vector.core.model_registry import ModelContract, ModelRegistry
from dbs_vector.core.profile_math import fitting_tiers
from dbs_vector.services.initializer.answers import InitAnswers, KindAnswers
from dbs_vector.services.initializer.kinds import EngineKindRegistry
from dbs_vector.services.initializer.render import (
    build_config_dict,
    dump_config_yaml,
    is_dbs_vector_checkout,
    profile_name_for,
    table_name_for,
    validate_rendered_config,
    workflow_for,
)

BUDGET = 21.0


def _answers(**overrides) -> InitAnswers:
    base = dict(
        engine_name="docs",
        model_key="granite-r2",
        kind_key="document",
        tier_key="medium",
        passage_prefix="",
        query_prefix="",
        db_path="/tmp/lancedb_dbs_vector",
        install_dir="/repo",
        config_path="config.yaml",
        mcp_path=".mcp.json",
        kind=KindAnswers(
            paths=["/tmp/notes"],
            ignore_patterns=[".#*", "*~", "*.tmp", ".DS_Store"],
            exclusion_filters=["excalidraw", "compressed_json"],
        ),
    )
    base.update(overrides)
    return InitAnswers(**base)


def _build(answers: InitAnswers) -> dict:
    contract = ModelRegistry.get(answers.model_key)
    kind = EngineKindRegistry.get(answers.kind_key)
    profile = kind.build_profile(contract, answers.tier_key, BUDGET)
    return build_config_dict(answers, profile, contract, kind)


def test_derived_names():
    assert table_name_for("md-granite") == "md_granite_vault"
    assert workflow_for("md-granite") == "md_granite_search"
    assert profile_name_for("docs", "medium") == "docs-medium"


def test_db_path_is_written_absolute():
    config = _build(_answers())
    assert config["system"]["db_path"] == "/tmp/lancedb_dbs_vector"


def test_engine_block_shape():
    config = _build(_answers())
    engine = config["engines"]["docs"]
    assert engine["model"] == "granite-r2"
    assert engine["mapper_type"] == "document"
    assert engine["chunker_type"] == "document"
    assert engine["table_name"] == "docs_vault"
    assert engine["workflow"] == "docs_search"
    assert engine["tuning_profile"] == "docs-medium"
    assert engine["paths"] == ["/tmp/notes"]


def test_similarity_floor_is_never_written():
    """Floors are deployment-local calibration evidence; a wizard must not
    invent one."""
    config = _build(_answers())
    assert "similarity_floor" not in config["engines"]["docs"]


def test_family_is_never_written():
    """family defaults to mapper_type; emitting it is redundant noise."""
    config = _build(_answers())
    assert "family" not in config["engines"]["docs"]


def test_prefixes_omitted_when_the_contract_carries_none():
    config = _build(_answers(model_key="granite-r2"))
    assert "passage_prefix" not in config["engines"]["docs"]
    assert "query_prefix" not in config["engines"]["docs"]


def test_prefixes_written_when_present():
    config = _build(
        _answers(
            model_key="gemma-bf16",
            tier_key="small",
            passage_prefix="title: none | text: ",
            query_prefix="task: search result | query: ",
        )
    )
    engine = config["engines"]["docs"]
    assert engine["passage_prefix"] == "title: none | text: "
    assert engine["query_prefix"] == "task: search result | query: "


def test_profile_block_carries_all_five_knobs():
    config = _build(_answers())
    profile = config["profiles"]["docs-medium"]
    assert set(profile) == {
        "max_token_length",
        "chunk_max_chars",
        "batch_size",
        "chunk_target_tokens",
        "chunk_max_tokens",
    }


def test_dump_yaml_preserves_key_order_and_carries_a_header():
    config = _build(_answers())
    text = dump_config_yaml(config, model_key="granite-r2", budget_gb=BUDGET)
    assert text.startswith("# Generated by `dbs-vector init`")
    assert "granite-r2" in text
    assert text.index("system:") < text.index("profiles:") < text.index("engines:")


def test_dump_yaml_round_trips():
    config = _build(_answers())
    text = dump_config_yaml(config, model_key="granite-r2", budget_gb=BUDGET)
    assert yaml.safe_load(text) == config


def test_validate_accepts_a_generated_config():
    config = _build(_answers())
    text = dump_config_yaml(config, model_key="granite-r2", budget_gb=BUDGET)
    validate_rendered_config(text)  # must not raise


def test_validate_accepts_a_watched_config():
    answers = _answers()
    answers.kind.watch_enabled = True
    config = _build(answers)
    text = dump_config_yaml(config, model_key="granite-r2", budget_gb=BUDGET)
    validate_rendered_config(text)


@pytest.mark.parametrize("model_key", ModelRegistry.keys())
def test_every_model_and_fitting_tier_produces_a_valid_config(model_key):
    """The §10 matrix. Task 2 checks derivation INVARIANTS; this checks that
    the resulting config survives the real validator end to end - the two are
    not the same, and only this one catches a rule that derivation does not
    model (engine naming, family, watch, table exclusivity)."""
    contract = ModelRegistry.get(model_key)
    tiers = fitting_tiers(contract)
    assert tiers, f"{model_key} fits no tier - the matrix would be vacuous"
    for tier in tiers:
        answers = _answers(model_key=model_key, tier_key=tier.key)
        config = _build(answers)
        text = dump_config_yaml(config, model_key=model_key, budget_gb=BUDGET)
        validate_rendered_config(text)


def test_a_synthetic_model_also_produces_a_valid_config(temp_model_registry):
    """Extends the matrix to a model that does not exist in the codebase,
    inside the fixture that keeps the registration from leaking."""
    temp_model_registry.register(
        "qwen3-embed-8b",
        ModelContract(
            model_name="mlx-community/qwen3-embedding-8b",
            vector_dimension=4096,
            model_max_token_length=40960,
            attention_mask_dtype=None,
            compute_dtype_bytes=2,
        ),
    )
    contract = temp_model_registry.get("qwen3-embed-8b")
    for tier in fitting_tiers(contract):
        answers = _answers(model_key="qwen3-embed-8b", tier_key=tier.key)
        config = _build(answers)
        text = dump_config_yaml(config, model_key="qwen3-embed-8b", budget_gb=BUDGET)
        validate_rendered_config(text)


def test_a_watched_config_validates_for_every_fitting_tier():
    """Rules 10 and 11 only fire when watch is enabled."""
    for model_key in ModelRegistry.keys():
        contract = ModelRegistry.get(model_key)
        for tier in fitting_tiers(contract):
            answers = _answers(model_key=model_key, tier_key=tier.key)
            answers.kind.watch_enabled = True
            text = dump_config_yaml(_build(answers), model_key=model_key, budget_gb=BUDGET)
            validate_rendered_config(text)


def test_validate_rejects_an_illegal_engine_name():
    """Rule 6: engine names must be MCP-tool-safe."""
    config = _build(_answers())
    config["engines"]["Bad Name"] = config["engines"].pop("docs")
    text = dump_config_yaml(config, model_key="granite-r2", budget_gb=BUDGET)
    with pytest.raises(ValueError, match="must match"):
        validate_rendered_config(text)


def test_validate_rejects_incoherent_chunk_budgets():
    """Rule 8: chunk_max_tokens must not exceed max_token_length."""
    config = _build(_answers())
    config["profiles"]["docs-medium"]["chunk_max_tokens"] = 99999
    text = dump_config_yaml(config, model_key="granite-r2", budget_gb=BUDGET)
    with pytest.raises(ValueError, match="chunk_max_tokens"):
        validate_rendered_config(text)


def test_a_foreign_project_is_not_a_dbs_vector_checkout(tmp_path):
    (tmp_path / "pyproject.toml").write_text(
        '[project]\nname = "some-other-app"\n', encoding="utf-8"
    )
    assert is_dbs_vector_checkout(tmp_path) is False


def test_a_real_checkout_is_recognised(tmp_path):
    (tmp_path / "pyproject.toml").write_text('[project]\nname = "dbs-vector"\n', encoding="utf-8")
    assert is_dbs_vector_checkout(tmp_path) is True


def test_a_nameless_project_is_rejected(tmp_path):
    """What every fixture used to write, and what the old check accepted."""
    (tmp_path / "pyproject.toml").write_text("[project]\n", encoding="utf-8")
    assert is_dbs_vector_checkout(tmp_path) is False


def test_a_missing_or_unparseable_manifest_is_not_a_checkout(tmp_path):
    assert is_dbs_vector_checkout(tmp_path) is False
    (tmp_path / "pyproject.toml").write_text("{ not toml", encoding="utf-8")
    assert is_dbs_vector_checkout(tmp_path) is False
